os: linux
dist: bionic
official_repo: &official_repo
  'lrzpellegrini/CI-Customized-BVLC-caffe-docker'
git:
  depth: false
env:
  global:
  - secure: 85mBVSFyxOtzB6zGMUPzzyVWmH45/tINVLsLFQaeD12i/qiLdLXBVyjtXItVauPtj5p2U6EL89Jved/tgnnk4/mP24oGgf4jIpVWWFPL0wS+1f1CmoKPaWRc7TibDWB4utuefrEopGGD6VU99AbPvokUgBpi/6k54davEplzCMm2/09/sc++d1LarpyFdllTOK0oiertUz4bQsXToAXsd9KsYJ+W/YGuEbps3D/BeoQzFR4YHcT722nHMn8TGgyzqUmT0oOkQQ1ZAznU+mfZPxs1C2fXaxPFjNpBwYS9HMnwFHorFOLEY9kQLs9ZLpcKbqqceixBGqyjmvoDbXvrd96+W3Ock1Nek0souMpr/Co37ayDqr//jS+Sn2gA1wDgJmEzpjHAjqK5KQmLRZQDs3b4Ycvr0SZxW6eUidC+/3F8PaRIW8uo3n6KGNOrk2ywbQnzILooAo4KUXBu4Pv7EOSwW9H0y2cjbi4uzNrObgMMYRAObsFBYN/SW3KzESRkzjAYq6ey8j15uBkfcxlbO1yZ6Ws9hgRCbpgxkI7DpdcKsyCUBd9BlmBtTSLiFffzhGy9P4fEMQb4guLa6pJIm1L5f4gbe3qpGSU7fvFSE212ghSmpbu0WdmTKa6qIo0dwGwjwLluN9d28zu+pHiEa6OW33QInkaQ4O+Sx64Pzik=
  - secure: FLdSq8dpNs8WzKdbooHhcSD9ISGruV2o8Hs2PZvzqTSBfxNH/omovH/CP4GEF87TSsb2X0M9oTmOapbiIp1Owm+k1UMAhmH2AKF0jeCSkQm3Rng+kRPkMTOyK6dg7I5QWI+T8FmxdpzGRsMOEx0TCgdmoFMeqMXMgbtXoVqXF/FHy5ZD1dvmDLpyLcGJbLO36d6dwtywWHvNn9QZ35rOzwsETGr9m2aEo2qevUbRq3n0OexIthiXK5EOTDtGhlHa0hFvCF0V1HJqx9DtWSeQ0MpVhDVJNvNZoFBVClW2AnuYFm0OHfQzdYiNnX2+YY3hHkQsJC3zkcRPlfa+SQGF50ypYf4v0NwZX4K8ZyIyaU7f+/ZhHaHaPH6sEigzy1JWDQjFH8qWs77eOndYggDCgLDCMlVuSjQyjU+VhNzFlWeRyfpClCF3IE2D69zeNHlXnIThqUfDVLzDrRD1ZmdgL4A5RqsAxZ5qcYVLzL986lH+NN0NC7Azz559GBD5pKMji1/MoxPVu2N9Zc3jJ4R+r+unI7P9GCK8789VGVjRKmfsIAqTV+yGl8I6R/jt0WJSSOfwWjSeWd+1ftJ2jrq1Zp6I34fBsOoeO8VZ/JMYODlx+7pErFnl+SmmYTsLiG0UW112c26CLjXtcXiLwOiOIoT+o15ZBOUv3JwzOcY4kSA=
  - GPU_IMAGE_TAG="gpu0.1.0"
  - CPU_IMAGE_TAG="cpu0.1.0"
  - GPU_IMAGE_TAG_LATEST="gpu_latest"
  - CPU_IMAGE_TAG_LATEST="cpu_latest"
  - GPU_IMAGE_DOCKERFILE="Dockerfile_gpu"
  - CPU_IMAGE_DOCKERFILE="Dockerfile_cpu"
  - BASE_IMAGE_NAME="unibo_milab_caffe"
services:
  - docker
script:
  - docker build -t $CPU_IMAGE_TAG -f $CPU_IMAGE_DOCKERFILE
  - docker tag $CPU_IMAGE_TAG $DOCKER_USERNAME/$BASE_IMAGE_NAME:$CPU_IMAGE_TAG
  - docker tag $CPU_IMAGE_TAG $DOCKER_USERNAME/$BASE_IMAGE_NAME:$CPU_IMAGE_TAG_LATEST
  - docker build -t $GPU_IMAGE_TAG -f $GPU_IMAGE_DOCKERFILE
  - docker tag $GPU_IMAGE_TAG $DOCKER_USERNAME/$BASE_IMAGE_NAME:$GPU_IMAGE_TAG
  - docker tag $GPU_IMAGE_TAG $DOCKER_USERNAME/$BASE_IMAGE_NAME:$GPU_IMAGE_TAG_lATEST
  - docker tag $GPU_IMAGE_TAG $DOCKER_USERNAME/$BASE_IMAGE_NAME:latest
deploy:
  - provider: script
    skip_cleanup: true
    script: |>
      set -e
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      docker push $DOCKER_USERNAME/$BASE_IMAGE_NAME:$CPU_IMAGE_TAG
      docker push $DOCKER_USERNAME/$BASE_IMAGE_NAME:$CPU_IMAGE_TAG_LATEST
      docker push $DOCKER_USERNAME/$BASE_IMAGE_NAME:$GPU_IMAGE_TAG
      docker push $DOCKER_USERNAME/$BASE_IMAGE_NAME:$GPU_IMAGE_TAG_lATEST
      docker push $DOCKER_USERNAME/$BASE_IMAGE_NAME:latest
      set +e
    on:
      repo: *official_repo
      branch: master
