FROM ubuntu:16.04

# TODO: optimize apt packages
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        git \
        ca-certificates \
        wget && \
	rm -rf /var/lib/apt/lists/*

RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.6.14-Linux-x86_64.sh -O ~/anaconda.sh && \
    /bin/bash ~/anaconda.sh -b -p /opt/conda && rm ~/anaconda.sh

ENV CAFFE_BUILD_ROOT=/opt/buildcaffe
ENV CAFFE_ROOT=/opt/caffe
WORKDIR $CAFFE_BUILD_ROOT

ARG CONDA=/opt/conda/bin/conda

ADD environment_for_cpu.yml .
RUN $CONDA env create -f environment_for_cpu.yml --override-channels -c conda-forge

ADD caffe $CAFFE_BUILD_ROOT

RUN /bin/bash -c "source /opt/conda/bin/activate caffecustomenv && \
	mkdir build && cd build && \
    	cmake -DCMAKE_CXX_STANDARD=11 -DCMAKE_PREFIX_PATH=/opt/conda/envs/caffecustomenv -DCMAKE_INSTALL_PREFIX=/opt/caffe -DBUILD_python=TRUE -DBUILD_matlab=FALSE -DBUILD_docs=FALSE -DBUILD_python_layer=TRUE -DCPU_ONLY=TRUE -Dpython_version=3 -DBLAS=open .. && \
    	cmake --build . --target install -- -j$(nproc)"

RUN rm -r $CAFFE_BUILD_ROOT
ENV PYCAFFE_ROOT $CAFFE_ROOT/python
ENV PYTHONPATH $PYCAFFE_ROOT:$PYTHONPATH
ENV PATH $CAFFE_ROOT/build/tools:$PYCAFFE_ROOT:/opt/conda/bin:$PATH
RUN echo "$CAFFE_ROOT/build/lib" >> /etc/ld.so.conf.d/caffe.conf && ldconfig

RUN echo "source activate caffecustomenv" > ~/.bashrc
ENV PATH /opt/conda/envs/caffecustomenv/bin:$PATH
WORKDIR /opt/project
